### ISSUE TITLE
Add basic stats to the admin page

### ISSUE THREAD

**Issue by wceolin** [zoonk/web#1]
**Is your feature request related to a problem? Please describe.**
It should be easier for admins to get some basic usage stats such as posts created, registered users, etc.

**Describe the solution you'd like**
Add a basic stats dashboard to the `/admin` page. Those stats should include the following data:

- Posts
- Posts per category (e.g. books, courses, examples, etc.)
- Topics
- Chapters
- Comments
- Registered users

**Tasks**

- [x] Create security rules for `admin` collection
- [x] Create function for updating posts count
- [x] Create function for updating post category count
- [x] Create function for updating topics count
- [x] Create function for updating chapters count
- [x] Create function for updating comments count
- [x] Create function for updating users count
- [x] Deploy firestore to staging
- [x] Deploy firestore to production
- [x] Deploy functions to staging
- [x] Deploy functions to production
- [x] Data migration
- [x] Update frontend to display stats
