### ISSUE TITLE
Send email notifications

### ISSUE THREAD

**Issue by wceolin** [zoonk/web#20]
**Is your feature request related to a problem? Please describe.**
When someone receives a notification, they need to visit Zoonk to see them.

**Describe the solution you'd like**
We should have an option to send email notifications.

**Additional context**
We should also have an option to unsubscribe to email notifications.

**Tasks**
- [x] Add language field to notifications
- [x] Add notification to the settings page
- [x] Create Cloud Function for sending an email when a notification is created
